### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by Freaky** [StrikeOrg/ulterius-server#45]

**Comment by andrewmd5** [comment]
Did you actually check the contents of the file? Everything is signed. In fact my partner replied to you on just how it works.

All the mechanics for verifying updates are done before you even get them.  All data is transmitted over HTTPS as well. I've gone ahead and added yet another check.

On another note

![](https://i.andrew.im/ep2lho.png)
![](http://i.andrew.im/gdnn8i.png)

Word of advice, being smug and condescending is not a good way to issue a bug report, offer feedback or try to get your point across. Fear mongering is unproductive and only serves to hinder progress.

That being said, this project supports pull request so if you're capable of contributing, please do. I'm not sure if you're new to coding but in the future, if you think you've found a major security issue follow these instructions 

"You should let the developer(s) know privately so that they have a chance to fix it. After that, if and when you go public with the vulnerability, you should allow the developer enough time to fix the problem and whoever is exposed to it enough time to upgrade their systems. Personally, I would allow the developer to make the announcement in a security bulletin in most cases rather than announcing it myself. At the very least, I would wait for confirmation that the vulnerability has been fixed. If you have time and have access to the source code, you could also provide a patch."

**Comment by Freaky** [comment]
Improper messages

**Comment by andrewmd5** [comment]
> Well, yeah. Sorry. But it's rather difficult 

Then grow up.
