### ISSUE TITLE
ScreenShare update issue (shows static image but still recognizes remote input)

### ISSUE THREAD

**Issue by sry9681** [StrikeOrg/ulterius-server#62]
I have recently come across an issue and don't know whether this issue should be posted on the client or server side of things but when I am connected through screenshare, it will only show me a static image. If I click anywhere it will register that click because if i disconnect and reconnect it will show what has changed but still give me a new static image.

Also worth mentioning that when you connect to screenshare and click the enlarge button (not the full size maximize button) and then disconnect, you are unable to un-enlarge the screen in order to navigate elsewhere.

**Comment by andrewmd5** [comment]
Hi @sry9681,

I'm currently rewriting the way the screen share agent communicates with the primary process to not be a hacky mess.

I'm confident with the new version issues like this will clean themselves up. I'm hoping to have it done in the next two days. A temporary solution is to restart the server from the settings menu when this occurs. 

The last part of your issue seems to be a client problem though, so I'll tag @FrobtheBuilder

**Comment by sry9681** [comment]
@Codeusa 

Would you be able to answer whether the new system for screenshare will capture more keys (like all the function keys, control key combinations, etc)?

**Comment by andrewmd5** [comment]
Function keys and combinations should work fine, keys like ctrl+alt+del are protected strokes which will require us to create a driver. This is on our road map.

We will also have to option to send keystrokes that would otherwise kill the browser like alt+f4
